### ISSUE TITLE
[FEATURE] New Release (v0.62.0?)

### ISSUE THREAD

**Issue by patrickdash** [prometheus-community/yet-another-cloudwatch-exporter#1560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Would it be possible for a new release to be published? There's been quite a few new features, bug fixes, and updates since the last release in June.

### What might the configuration look like?

n/a

### Anything else?

https://github.com/nerdswords/yet-another-cloudwatch-exporter/compare/v0.61.2...master

**Comment by cristiangreco** [comment]
Thanks for the patience @patrickdash, we've been busy with the move of the project to prometheus-community, will cut a release as soon as things are settled.
