### ISSUE TITLE
0.31 docker image, target group not update when without docker reset

### ISSUE THREAD

**Issue by chagainota** [prometheus-community/yet-another-cloudwatch-exporter#472]
Hi

I'm monitoring health host count with yace solution, in latest version I have a bug.
When I start the docker and I have exist Target Group it pull data from cloud watch correctly.
But when I add a new target group it not monitor it correctly, it reply NaN. when I restart the docker it become OK again.

Thx
Chagai

**Comment by thomaspeitz** [comment]
Should be fixed

**Comment by chagainota** [comment]
Thx for the update! i will test it and let you know

**Comment by thomaspeitz** [comment]
Closed due to inactivity.
